server:
  session:
    timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
  port: 8001

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/wboot_sqlite.db
    username: root
    password: root
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  profiles:
        active: dev

mybatis:
  mapper-locations: mybatis/**/**Mapper.xml
  type-aliases-package: com.wboot.**.model

#日志输出
logging:
  level:
    com.wboot: debug

